"""add fbid googleid

Revision ID: 02ff98d9e04a
Revises: 8fb8e502b00a
Create Date: 2022-02-20 21:25:18.829212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ff98d9e04a'
down_revision = '8fb8e502b00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_facebook_id_key', 'users', type_='unique')
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.create_unique_constraint('users_facebook_id_key', 'users', ['facebook_id'])
    # ### end Alembic commands ###
