"""add facebook_id google_id column

Revision ID: 8fb8e502b00a
Revises: f8d6fc280b3e
Create Date: 2022-02-20 21:20:39.501625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb8e502b00a'
down_revision = 'f8d6fc280b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'facebook_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.create_unique_constraint(None, 'users', ['facebook_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###
